Models/ErrorViewModel.cs
namespace SQL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Table.cs
namespace SQL.Models
{
    public class Table
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }

        public string Email { get; set; }
        public double Contact { get; set; }
        public Table()
        {

        }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SQL.Models;
using System.Diagnostics;

namespace SQL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TablesController.cs
#nullable disable
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SQL.Data;
using SQL.Models;

namespace SQL.Controllers
{
    public class TablesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TablesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Tables
        public async Task<IActionResult> Index(string SearchString)
        {
            var names = from m in _context.Table
                        select m;
            if (!String.IsNullOrEmpty(SearchString))
            {
                names = names.Where(s => s.Name!.Contains(SearchString));
            }
            return View(await names.ToListAsync());


        }

        // GET: Tables/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var table = await _context.Table
                .FirstOrDefaultAsync(m => m.ID == id);
            if (table == null)
            {
                return NotFound();
            }

            return View(table);
        }

        public IActionResult Search()
        {
            return View();
        }
        // GET: Tables/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tables/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Address,Email,Contact")] Table table)
        {
            if (ModelState.IsValid)
            {
                _context.Add(table);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(table);
        }

        // GET: Tables/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var table = await _context.Table.FindAsync(id);
            if (table == null)
            {
                return NotFound();
            }
            return View(table);
        }

        // POST: Tables/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Address,Email,Contact")] Table table)
        {
            if (id != table.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(table);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TableExists(table.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(table);
        }

        // GET: Tables/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var table = await _context.Table
                .FirstOrDefaultAsync(m => m.ID == id);
            if (table == null)
            {
                return NotFound();
            }

            return View(table);
        }

        // POST: Tables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var table = await _context.Table.FindAsync(id);
            _context.Table.Remove(table);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TableExists(int id)
        {
            return _context.Table.Any(e => e.ID == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SQL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SQL.styles.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="/Images/favicon.ico" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>

<style>
    body{
        color:white;
        font-weight:bold;
        background: rgb(0,0,0);
        background: linear-gradient(180deg, rgba(0,0,0,1) 0%, rgba(14,46,82,1) 91%);
    }

    #a:hover {
        background-color: yellow;
        }
</style>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <button class="btn btn-outline-dark" style="margin-left:10px" id="btn_anim">></button>
            <div class="container-fluid col-1" id="main">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SQL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                     
                </button>
               
                <div class="container" id="fluid_anim">    
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a id="a" class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a id="a" class="nav-link text-dark" asp-area="" asp-controller="Tables" asp-action="Search">Search</a>
                        </li>
                        <li class="nav-item">
                            <a id="a" class="nav-link text-dark" asp-area="" asp-controller="Tables" asp-action="Index">Account</a>
                        </li>
                        <li class="nav-item">
                            <a id="a" class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                    </ul>
                </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="/js/fluid.js"></script>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SQL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Tables/Create.cshtml
@model SQL.Models.Table

@{
    ViewData["Title"] = "Create";
}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">

   <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
   <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>

<style>

    #top{
        display:flex;
        justify-content:center;
        color:white;
        font-weight:bold;
    }

    #body{
    display:flex;
    justify-content:center; 
    margin-top:10px
    }

     .ui-menu-item{
        background-color:black;
        color:white;
    }

</style>

<div class="row" id="top"><h3 class="col-3">Add new records</h3></div>

<div class="container" id="body">    
<div class="row" style="background-color:black"><span class="border-top-0"></span>
    <div class="col-md-12" style="color:white;font-weight:bold">
        <form asp-action="Create" class="needs-validation" novalidate>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="margin-top:5px">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" placeholder="Fullname" required/>
                <span asp-validation-for="Name" class="text-danger"></span>
                <div class="valid-feedback">
                    Perfect!
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" id="address" placeholder="District" required/>
                <span asp-validation-for="Address" class="text-danger"></span>
                 <div class="valid-feedback">
                    Perfect!
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" placeholder="example@gmail.com" required/>
                <span asp-validation-for="Email" class="text-danger"></span>
                 <div class="valid-feedback">
                    Perfect!
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Contact" class="control-label"></label>
                <input asp-for="Contact" class="form-control" placeholder="+977" required/>
                <span asp-validation-for="Contact" class="text-danger"></span>
                 <div class="valid-feedback">
                    Perfect!
                </div>
            </div>
            <div class="form-group" style="margin-top:5px;margin-bottom:10px;">
                <button type="submit" value="Create" class="btn btn-outline-dark" style="color:white;font-weight:bold"><i class="bi bi-file-plus"></i>Create</button>
                 <a class="btn btn-outline-dark" style="color:white;font-weight:bold" asp-action="Index"><i class="bi bi-caret-left"></i>Back to List</a>
            </div>
        </form>
     </div>
   </div>
</div>

<script src="/js/autoComplete.js"></script>
<script src="/js/validate.js"></script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tables/Delete.cshtml
@model SQL.Models.Table

@{
    ViewData["Title"] = "Delete";
}

<style>
    #body{
        display:flex;
        justify-content:center; 
        margin-top:10px;
        background-color:black;
        color:white;
        }
</style>

<h3>Delete</h3>

<div>
  <div class="container" id="body"> 
    <dl class="row" style="margin-top:10px">
        <dt class = "col-sm-2" id="text">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact)
        </dd>
       
        <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <button type="submit" value="Delete" class="btn btn-outline-dark" style="color:white;font-weight:bold"><i class="bi bi-trash"></i>Delete</button>
         <a style="color:white;font-weight:bold" id="a" class="btn btn-outline-dark"asp-action="Index"><i class="bi bi-caret-left"></i>Back to List</a>
    </form>
    
    </dl>
    
    </div>
    
</div>

Views/Tables/Details.cshtml
@model SQL.Models.Table

@{
    ViewData["Title"] = "Details";
}

<style>
    #body{
        display:flex;
        justify-content:center; 
        margin-top:10px;
        background-color:black;
        color:white;
        }

    #a{
        color:white;
        font-weight:bold;
    }
</style>

<h3>Details</h3>

<div>
    <div class="container" id="body"> 
    <dl class="row" style="margin-top:10px">
        <dt class = "col-sm-2" id="text">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact)
        </dd>

        <div>
            <a id="a" class="btn btn-outline-dark" style="text-decoration:none" asp-action="Edit" asp-route-id="@Model?.ID"><i class="bi bi-pencil-square"></i>Edit</a>
            <a id="a" class="btn btn-outline-dark" asp-action="Index"><i class="bi bi-caret-left"></i>Back to List</a>
        </div>
    </dl>
</div>
</div>

Views/Tables/Edit.cshtml
@model SQL.Models.Table

@{
    ViewData["Title"] = "Edit";
}

    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">

   <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
   <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>

<style>
       #top{
        display:flex;
        justify-content:center;
        color:white;
        font-weight:bold;
        }

    #body{
    display:flex;
    justify-content:center; 
    margin-top:10px
    }

     .ui-menu-item{
        background-color:black;
        color:white;
    }

</style>

<div class="row" id="top"><h3 class="col-3">Edit Records</h3></div>

<div class="container" id="body">
<div class="row" style="background-color:black"><span class="border-top-0"></span>
    <div class="col-md-12" style="color:white;font-weight:bold">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" id="address" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact" class="control-label"></label>
                <input asp-for="Contact" class="form-control" />
                <span asp-validation-for="Contact" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-top:5px;margin-bottom:10px;color:white;font-weight:bold">
                 <button type="submit" value="Save" class="btn btn-outline-dark" style="color:white;font-weight:bold"><i class="bi bi-pencil-square"></i>Save</button>
                 <a class="btn btn-outline-dark" style="color:white;font-weight:bold" asp-action="Index"><i class="bi bi-caret-left"></i>Back to List</a>
            </div>
        </form>
    </div>
    </div>
</div>
<script src="/js/autoComplete.js"></script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tables/Index.cshtml
@model IEnumerable<SQL.Models.Table>

@{
    ViewData["Title"] = "Account Information";
}

<style>
    #a,#table{
        color:white;
        font-weight:bold;
    }
</style>

<h1>Account Information</h1>

<p>
    <a id="a" class="btn btn-outline-info" asp-action="Create"><i class="bi bi-file-plus"></i>Create New</a>
</p>
<table class="table" id="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contact)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contact)
            </td>
            <td>
                <div class="container">
                    <a id="a" class="btn btn-outline-info" asp-action="Edit" asp-route-id="@item.ID"><i class="bi bi-pencil-square"></i>Edit</a> 
                    <a id="a" class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.ID"><i class="bi bi-archive"></i>Details</a> 
                    <a id="a" class="btn btn-outline-info" asp-action="Delete" asp-route-id="@item.ID"><i class="bi bi-trash"></i>Delete</a>
                </div>
              
            </td>
        </tr>
}
    </tbody>
</table>

Views/Tables/Search.cshtml
@{
    ViewData["Title"] = "Search";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search</title>
</head>
<body>
     <h1>Search</h1>

     <form asp-controller="Tables" asp-action="Index">
    <p>
        <input type="text" name="SearchString" class="form-control" placeholder="Search by name"/>
        <input style="margin-top:5px;color:white;font-weight:bold;" type="submit" class="btn btn-outline-dark" value="Search" />
    </p>
    </form>
  
</body>
</html>